version: '3.1'

services:
    
  config-server:
    image: maltor/config-server
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CERTIFICATE_CHECK: 0 
    ports:
    - "8888:8888"
  
#  rabbitmq:
#    image: rabbitmq:3.6-management
#    container_name: rabbitmq
#    ports:
#     - "5672:5672"
     
#  auth-server:
#    image: maltor/auth-server
#    container_name: auth-server
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#     - "9999:9999"
#       
#  resource-server:
#    image: maltor/resource-server
#    container_name: resource-server
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#     - "9090:9090"   
 
  discovery-server:
    image: maltor/discovery-server
    container_name: discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CERTIFICATE_CHECK: 0 
    ports:
    - "8761:8761"
    
  db:
    image: postgres:10
    container_name: postgres
    restart: always
    environment:
        POSTGRES_USER: shop
        POSTGRES_PASSWORD: shop
        POSTGRES_DB: shop-db
    ports:
    - "5432:5432"
    